# Config file for automatic testing at travis-ci.org

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - pip install -U tox-travis
 - npm install -g elm@0.18 elm-test@0.18 elm-github-install

# Command to run tests, e.g. python setup.py test
script: tox
