# Config file for automatic testing at travis-ci.org

env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.21.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install:
 - pip install -U tox-travis
 - npm install -g elm@0.18 elm-test@0.18 elm-github-install

# Command to run tests, e.g. python setup.py test
script: tox
