[metadata]
author = Luke Plant
author_email = L.Plant.98@cantab.net
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Developers
    License :: OSI Approved :: MIT License
    Natural Language :: English
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.4
    Programming Language :: Python :: 3.5
    Programming Language :: Python :: 3.6
    Programming Language :: Python :: 3.7
description = Fluent i18n solution for Elm
license = MIT license
keywords = elm_fluent
name = elm_fluent
url = https://github.com/elm-fluent/elm-fluent
version = 0.6.0

[options]
install_requires =
    Click>=6.0
    fluent.syntax>=0.15
    attrs>=18
    language-tags>=0.4.4
    beautifulsoup4>=4.6.3
    lxml>=4.2.4
    watchdog>=0.8.3
    fs>=2.4.2
packages = find:
package_dir = =src
zip_safe = False

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    ftl2elm=elm_fluent.cli:main

[bumpversion]
current_version = 0.1.0
commit = True
tag = True

[bumpversion:file:setup.py]
search = version='{current_version}'
replace = version='{new_version}'

[bumpversion:file:elm_fluent/__init__.py]
search = __version__ = '{current_version}'
replace = __version__ = '{new_version}'

[flake8]
exclude = docs,.tox,.eggs
max-line-length = 120
ignore = E501,W503

[isort]
multi_line_output = 3
include_trailing_comma = True
force_grid_wrap = 0
use_parentheses = True
line_length = 88
combine_as_imports = True
skip = docs,.tox,.eggs
known_third_party = click,language_tags,pyvirtualdisplay,mock
known_first_party = elm_fluent

[tool:pytest]
norecursedirs = elm-stuff
markers =
    slow
